### ISSUE TITLE
update version in windows readme

### ISSUE THREAD

**Issue by radix42** [vaklinov/zcash-swing-wallet-ui#18]
Latest is now 1.0.8-1 at https://zcash.dl.mercerweiss.com/zcash-win-v1.0.8-1.zip

**Comment by LeRobert** [comment]
I have just tried to run the 0.65-beta wallet with zcash-win-1.0.8-1. Win 10, Java 1.8.0-131. 
When the wallet form opens it is empty (no controls), soon followed by a pop-up message with "Error" in the title. Also this form is empty.
I was following these steps: https://github.com/vaklinov/zcash-swing-wallet-ui/blob/master/docs/Readme-Windows.md
What would be the solution?

**Comment by vaklinov** [comment]
The problem is that due to ZCash interfacing changes in version 1.0.8, you need the very latest GUI wallet compiled from source to work with it. Even binary version 0.65 does not work as you observed. So I need to make a new binary release and update the Windows readme after that...

Until this is done, please compile the latest GUI Wallet version (0.68) from source - I have tested the latest source to work with ZCash 1.0.8.

**Comment by vaklinov** [comment]
I have made a new binary release 0.69-beta:
https://github.com/vaklinov/zcash-swing-wallet-ui/blob/master/docs/Release_0.69-beta.md
that works with the latest ZCash.

**Comment by vaklinov** [comment]
Document (windows readme) is updated:
https://github.com/vaklinov/zcash-swing-wallet-ui/blob/master/docs/Readme-Windows.md
