### ISSUE TITLE
Wallet balance disappears temporarily after spending ZCash

### ISSUE THREAD

**Issue by vaklinov** [vaklinov/zcash-swing-wallet-ui#2]
When you spend from a T address the balance "appears to disappear" for 1-2 minutes. Then it comes back - minus what was spent, the remainder is sent to another T address.  The GUI wallet currently users z_gettotalbalance without parameters - this is a problem (users may perceive temporarily that their balance is lost). This is because recent transactions have not been confirmed by peers.

GUI Wallet can use
`zcash-cli z_gettotalbalance 0`
To see the "unconfirmed" balances while you wait for them to be confirmed

https://forum.z.cash/t/zcash-desktop-gui-wallet/2129/19

**Comment by vaklinov** [comment]
Fully fixed for the Overview TAB and partly for Addresses/Sending - issue remains open for now.

**Comment by vaklinov** [comment]
Fixed.

**Comment by tellurium999** [comment]
Hello, I use the experimental build for windows.
Version 0.58 beta and when i send from t-adress to another t-adress the remaining cash is sent to a newly created t-adress in the wallet. Is this normal ? It's very annoying because it is usually less than the tx fee and i cannot get this cash back...
Thanks for your work, greatly appreciate it :)

**Comment by vaklinov** [comment]
Hi,
   Yes. When sending from a T address, it is the standard/expected 
behavior to have the remaining funds sent to another T address. This 
improves privacy. You could also try to use the z_sendmany command via 
command line - should show the same behavior.

This is possible to change in GUI wallet code - I will keep it in mind 
for the future (would require quite a few changes/testing though).
